add switch database method sqflite adapter
Jaguar-dart/jaguar_orm pull request #72
Opened 2018-09-28 14:49 UTC by jaumard

Little story about this :) 

In our app we need one database per user, so each time there a login we need to switch the database to another one. Problem with the current way of working of jaguar is that the Apater is needed in every "Bean" so if we want to switch database we need to switch Adapter, meaning recreate every "Bean" that are in multiple place of the app... so it's not really doable/safe to switch the adapter. Instead what we can if switch the underlying connection to a new one each time the user login. 
That why `switchDatabase` is useful

2018-09-28 16:49 UTC, tejainece commented
Hi,

`Adapter` is immutable. You have to maintain a connection per user resulting in one adapter per connection which in turn resulting in a bean per connection.

2018-09-28 17:04 UTC, jaumard commented
Hum that will not work for me... it will basically be equal to just restart the app from scratch for each user... Bean are not singleton so you can have references of them everywhere in the app... only way you're sure there no reference in some redux middleware it to restart from scratch... 
One way that I could achieve that on my side would be to change the internal use of _connexion to the public getter "connection". Like this it will allow my to override the adapter and do this switchDatabase. 

Is that changes ok for you then ?

2018-09-28 17:11 UTC, jaumard commented
just pushed that changes and remove switchDatabase, let me know if it's ok for you like this @tejainece :) I'll do it on my side

2018-09-28 17:25 UTC, tejainece requested changes

2018-09-28 17:25 UTC, tejainece commented on sqflite/lib/src/adapter.dart
> +  Future<void> close() => connection.close();
Why not `_connection`?

2018-09-28 17:28 UTC, tejainece commented on sqflite/pubspec.yaml
> +- Aumard Jimmy <jimmy.aumard@gmail.com>
Move your name to the top. You basically built this.

2018-09-29 06:45 UTC, tejainece approved these changes
LGTM

2018-09-29 06:45 UTC, merged